### ISSUE TITLE
Linux OpenFilePickerAsync Pop up prompt "Portal is ready"

### ISSUE THREAD

**Issue by mansai** [AvaloniaUI/AvaloniaUI.QuickGuides#28]
OS:ubuntu-22.04.3-desktop-amd64

![image](https://github.com/AvaloniaUI/AvaloniaUI.QuickGuides/assets/3213405/0661a4bd-656b-4d31-9d48-ed4155ff7a7a)

![image](https://github.com/AvaloniaUI/AvaloniaUI.QuickGuides/assets/3213405/db12c342-746c-4c04-b125-bfd197738af6)

**Comment by maxkatz6** [comment]
Looks like an issue of your OS Distro, specifically mishandling of FreeDesktop FileChooser standard implementation.

**Comment by mansai** [comment]
Updated to the latest version, problem resolved
![image](https://github.com/AvaloniaUI/AvaloniaUI.QuickGuides/assets/3213405/ae2cf598-19fc-413d-ab41-8e81615f6f08)
